apiVersion: 1
datasources:
  - name: CabinDB
    type: postgres
    url: cabin-postgres:5432
    database: cabin
    user: cabin
    secureJsonData:
      password: "${POSTGRES_PASSWORD}"
    jsonData:
      sslmode: disable
      timescaledb: true
